# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeinfo',
            old_name='title',
            new_name='ttitle',
        ),
    ]
